#!/usr/bin/with-contenv sh

[ -f /config/cloudflare.conf ] || exit 0

. /app/cloudflare.sh

if [ "$DELETE_ON_STOP" == "true" ]; then
  while IFS= read -r CLOUDFLARE_CONFIG_LINE; do
	eval $CLOUDFLARE_CONFIG_LINE

	echo "Deleting CloudFlare DNS record $CF_RECORD_NAME..."

	update=$(deleteDnsRecord $CF_ZONE_ID $CF_RECORD_ID)

	if [ "$update" == "null" ]; then
		echo "ERROR: Failed to delete CloudFlare DNS record $CF_RECORD_NAME"
	else
	    echo "CloudFlare DNS record $CF_RECORD_NAME deleted successfully."
	fi
  done < /config/cloudflare.conf
else
  echo "Not going to delete zone record. Deleting the zone record on container stop is disable by default."
fi
