#!/usr/bin/with-contenv sh

. /app/cloudflare.sh

# Load ZONE and SUBDOMAIN vars from Docker Swarm secrets, if available:
if [ -f "$SUBDOMAIN_FILE" ]; then
    SUBDOMAIN=$(cat $SUBDOMAIN_FILE)
fi
if [ -f "$ZONE_FILE" ]; then
    ZONE=$(cat $ZONE_FILE)
fi

# Verify the $EMAIL and $API_KEY env variables are valid
statusCode=$(verifyToken)

if [ "$statusCode" != "200" ]; then
  echo "----------------------------------------------------------------"
  echo "ERROR: Invalid CloudFlare Credentials - $statusCode"
  echo "----------------------------------------------------------------"
  if [ -z "$EMAIL" ]
    then
      echo "Make sure the API_KEY is correct. You can"
      echo "get your scoped CloudFlare API Token here:"
      echo "https://dash.cloudflare.com/profile/api-tokens"
    else
      echo "Make sure the EMAIL and API_KEY variables are correct. You can"
      echo "get your CloudFlare API Key here:"
      echo "https://www.cloudflare.com/a/profile"
      echo
      echo "If you are using a zone token please remove the EMAIL variable"
      echo "from this container."
  fi
  echo
  echo "----------------------------------------------------------------"
  exit 1
fi

# Get the ID of the zone from the CloudFlare API
CFZoneId=$(getZoneId)

if [ "$CFZoneId" == "null" ]; then
  echo "----------------------------------------------------------------"
  echo "ERROR: Zone for $ZONE was not found in your CloudFlare Account"
  echo "----------------------------------------------------------------"
  echo "Make sure the ZONE variable is correct and the domain exists"
  echo "in your CloudFlare account. You can add a new domain here:"
  echo
  echo "https://www.cloudflare.com/a/add-site"
  echo "----------------------------------------------------------------"
  exit 1
fi

echo "DNS Zone: $ZONE ($CFZoneId)"

# Check we can get the current public ip address
PublicIpAddress=$(getPublicIpAddress)

if [ ! -z ${INTERFACE+x} ]; then
  PublicIpAddress=$(getLocalIpAddress)
fi

if [ "$PublicIpAddress" == "" ]; then
  echo "----------------------------------------------------------------"
  if [ "$RRTYPE" == "AAAA" ]; then
    echo "ERROR: Failed To Get Public IPv6 Address"
    echo "----------------------------------------------------------------"
    echo "You must be running Docker with IPv6 support enabled or this"
    echo "container with host networking enabled."
    echo
    echo "Add '--net=host' to your docker run command or if using"
    echo "docker-compose add 'network_mode: host' to this service."
  else
    echo "ERROR: Failed To Get Public IPv4 Address"
  fi
  echo "----------------------------------------------------------------"
  exit 1
fi

# Get the ID of the dns record from the CloudFlare API
CFDnsRecordName=$(getDnsRecordName)
CFDnsRecordId=$(getDnsRecordId $CFZoneId $CFDnsRecordName)

# If the dns record does not exist, create it now.
if [ "$CFDnsRecordId" == "null" ]; then
  echo "DNS record for '$CFDnsRecordName' was not found in $ZONE zone. Creating now..."
  CFDnsRecordId=$(createDnsRecord $CFZoneId $CFDnsRecordName $PublicIpAddress)

  if [ "$CFDnsRecordId" == "null" ]; then
    echo "----------------------------------------------------------------"
    echo "ERROR: Failed to create DNS record '$CFDnsRecordName'"
    echo "----------------------------------------------------------------"
    exit 1
  fi

fi

echo "DNS Record: $CFDnsRecordName ($CFDnsRecordId)"
echo "CF_ZONE_ID=\"$CFZoneId\" CF_RECORD_ID=\"$CFDnsRecordId\" CF_RECORD_NAME=\"$CFDnsRecordName\"" > /config/cloudflare.conf
echo "$CRON	/etc/cont-init.d/50-ddns" > /var/spool/cron/crontabs/root